[package]
name = "chip_8"
version = "0.1.0"
authors = ["andrew644 <andrew644@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
